"""add message2

Revision ID: d9c401c86d45
Revises: afbeb677a3c8
Create Date: 2020-08-30 13:36:43.184230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c401c86d45'
down_revision = 'afbeb677a3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_to_user_id'), 'messages', ['to_user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_to_user_id'), table_name='messages')
    op.drop_column('messages', 'to_user_id')
    # ### end Alembic commands ###
